// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['pttclient']['PTTClient']['Close']();
}

export function FetchLivePosts() {
  return window['go']['pttclient']['PTTClient']['FetchLivePosts']();
}

export function FetchPostMessagesByAID(arg1, arg2) {
  return window['go']['pttclient']['PTTClient']['FetchPostMessagesByAID'](arg1, arg2);
}

export function FetchPostMessagesBySN(arg1, arg2) {
  return window['go']['pttclient']['PTTClient']['FetchPostMessagesBySN'](arg1, arg2);
}

export function GetHotBoards() {
  return window['go']['pttclient']['PTTClient']['GetHotBoards']();
}

export function GotoBoard(arg1) {
  return window['go']['pttclient']['PTTClient']['GotoBoard'](arg1);
}

export function Lock() {
  return window['go']['pttclient']['PTTClient']['Lock']();
}

export function Login(arg1, arg2) {
  return window['go']['pttclient']['PTTClient']['Login'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['pttclient']['PTTClient']['SendMessage'](arg1, arg2);
}

export function StartUp(arg1) {
  return window['go']['pttclient']['PTTClient']['StartUp'](arg1);
}

export function Unlock() {
  return window['go']['pttclient']['PTTClient']['Unlock']();
}
