// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consts} from '../models';
import {pttclient} from '../models';
import {pttcrawler} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function FetchLivePosts():Promise<Array<consts.Post>>;

export function FetchPostMessagesByAID(arg1:string,arg2:string):Promise<Array<pttclient.Message>>;

export function FetchPostMessagesBySN(arg1:string,arg2:string):Promise<Array<pttclient.Message>>;

export function GetHotBoards():Promise<Array<pttcrawler.HotBoard>>;

export function GotoBoard(arg1:string):Promise<Array<consts.Post>>;

export function Lock():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:pttclient.MessageType,arg2:string):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;

export function Unlock():Promise<void>;
