// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate():Promise<Record<string, string>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function PerformUpdate():Promise<string>;

export function Quit():Promise<void>;

export function Restart():Promise<void>;
